######################################################################
# Automatically generated by qmake (3.0) Mo. Dez. 9 10:19:01 2019
######################################################################

TEMPLATE = app
TARGET = heapsort
INCLUDEPATH += .

# Input
HEADERS += heapsort.h \
    config.h
SOURCES += heapsort.cpp main.cpp
